# Generated by Django 5.2.6 on 2025-09-06 06:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='নাম')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='কোড')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='payment_methods/', verbose_name='আইকন')),
                ('description', models.TextField(blank=True, null=True, verbose_name='বিবরণ')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='প্রসেসিং ফি (৳)')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ন্যূনতম পরিমাণ (৳)')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='সর্বোচ্চ পরিমাণ (৳)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
            ],
            options={
                'verbose_name': 'পেমেন্ট পদ্ধতি',
                'verbose_name_plural': 'পেমেন্ট পদ্ধতি',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'ক্যাশ অন ডেলিভারি'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank_transfer', 'ব্যাংক ট্রান্সফার'), ('card', 'কার্ড')], max_length=20, verbose_name='পেমেন্ট পদ্ধতি')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='পরিমাণ (৳)')),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমান'), ('processing', 'প্রক্রিয়াধীন'), ('completed', 'সম্পন্ন'), ('failed', 'ব্যর্থ'), ('cancelled', 'বাতিল'), ('refunded', 'ফেরত')], default='pending', max_length=20, verbose_name='অবস্থা')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='লেনদেন আইডি')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='পেমেন্ট রেফারেন্স')),
                ('payment_details', models.JSONField(blank=True, null=True, verbose_name='পেমেন্ট বিবরণ')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='পেমেন্ট দেওয়া হয়েছে')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেট হয়েছে')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='অর্ডার')),
            ],
            options={
                'verbose_name': 'পেমেন্ট',
                'verbose_name_plural': 'পেমেন্ট',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='কর্ম')),
                ('status', models.CharField(max_length=20, verbose_name='অবস্থা')),
                ('message', models.TextField(blank=True, null=True, verbose_name='বার্তা')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='প্রতিক্রিয়া ডেটা')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='সময়')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment', verbose_name='পেমেন্ট')),
            ],
            options={
                'verbose_name': 'পেমেন্ট লেনদেন',
                'verbose_name_plural': 'পেমেন্ট লেনদেন',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='পরিমাণ (৳)')),
                ('reason', models.TextField(verbose_name='কারণ')),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমান'), ('processing', 'প্রক্রিয়াধীন'), ('completed', 'সম্পন্ন'), ('failed', 'ব্যর্থ'), ('cancelled', 'বাতিল')], default='pending', max_length=20, verbose_name='অবস্থা')),
                ('refund_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='রিফান্ড রেফারেন্স')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='প্রক্রিয়াকরণ হয়েছে')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='পেমেন্ট')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='প্রক্রিয়াকরণ করেছেন')),
            ],
            options={
                'verbose_name': 'রিফান্ড',
                'verbose_name_plural': 'রিফান্ড',
                'ordering': ['-created_at'],
            },
        ),
    ]
