# Generated by Django 5.2.6 on 2025-09-06 06:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('description', models.TextField(blank=True, null=True, verbose_name='বিবরণ')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ডেলিভারি ফি (৳)')),
                ('estimated_delivery_time', models.PositiveIntegerField(help_text='Estimated delivery time in minutes', verbose_name='আনুমানিক ডেলিভারি সময় (মিনিট)')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
            ],
            options={
                'verbose_name': 'ডেলিভারি এলাকা',
                'verbose_name_plural': 'ডেলিভারি এলাকা',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAgentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='অক্ষাংশ')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='দ্রাঘিমাংশ')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='ঠিকানা')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='সময়')),
                ('delivery_agent', models.ForeignKey(limit_choices_to={'user_type': 'delivery_agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='ডেলিভারি এজেন্ট')),
            ],
            options={
                'verbose_name': 'ডেলিভারি এজেন্ট অবস্থান',
                'verbose_name_plural': 'ডেলিভারি এজেন্ট অবস্থান',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='নির্ধারিত হয়েছে')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='আনুমানিক ডেলিভারি সময়')),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='প্রকৃত ডেলিভারি সময়')),
                ('delivery_notes', models.TextField(blank=True, null=True, verbose_name='ডেলিভারি নোট')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='নির্ধারিত করেছেন')),
                ('delivery_agent', models.ForeignKey(limit_choices_to={'user_type': 'delivery_agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL, verbose_name='ডেলিভারি এজেন্ট')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment', to='orders.order', verbose_name='অর্ডার')),
            ],
            options={
                'verbose_name': 'ডেলিভারি নির্ধারণ',
                'verbose_name_plural': 'ডেলিভারি নির্ধারণ',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='রেটিং (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='মন্তব্য')),
                ('rated_at', models.DateTimeField(auto_now_add=True, verbose_name='রেটিং দেওয়া হয়েছে')),
                ('delivery_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='delivery.deliveryassignment', verbose_name='ডেলিভারি নির্ধারণ')),
            ],
            options={
                'verbose_name': 'ডেলিভারি রেটিং',
                'verbose_name_plural': 'ডেলিভারি রেটিং',
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'নির্ধারিত'), ('picked_up', 'পিকআপ সম্পন্ন'), ('in_transit', 'পথে'), ('delivered', 'ডেলিভারি সম্পন্ন'), ('failed', 'ব্যর্থ'), ('returned', 'ফেরত')], max_length=20, verbose_name='অবস্থা')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='অবস্থান')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='নোট')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='সময়')),
                ('delivery_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='delivery.deliveryassignment', verbose_name='ডেলিভারি নির্ধারণ')),
            ],
            options={
                'verbose_name': 'ডেলিভারি অবস্থা',
                'verbose_name_plural': 'ডেলিভারি অবস্থা',
                'ordering': ['-timestamp'],
            },
        ),
    ]
