# Generated by Django 5.2.6 on 2025-09-06 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('widget_type', models.CharField(choices=[('chart', 'চার্ট'), ('table', 'টেবিল'), ('metric', 'মেট্রিক'), ('list', 'তালিকা')], max_length=20, verbose_name='উইজেট ধরন')),
                ('description', models.TextField(blank=True, null=True, verbose_name='বিবরণ')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='অবস্থান')),
                ('config', models.JSONField(blank=True, null=True, verbose_name='কনফিগারেশন')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
            ],
            options={
                'verbose_name': 'ড্যাশবোর্ড উইজেট',
                'verbose_name_plural': 'ড্যাশবোর্ড উইজেট',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='প্রশ্ন')),
                ('answer', models.TextField(verbose_name='উত্তর')),
                ('category', models.CharField(choices=[('general', 'সাধারণ'), ('orders', 'অর্ডার'), ('delivery', 'ডেলিভারি'), ('payment', 'পেমেন্ট'), ('account', 'অ্যাকাউন্ট'), ('technical', 'প্রযুক্তিগত')], max_length=20, verbose_name='বিভাগ')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রম')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেট হয়েছে')),
            ],
            options={
                'verbose_name': 'প্রায়শই জিজ্ঞাসিত প্রশ্ন',
                'verbose_name_plural': 'প্রায়শই জিজ্ঞাসিত প্রশ্ন',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('orders', 'অর্ডার'), ('revenue', 'রাজস্ব'), ('customers', 'গ্রাহক'), ('deliveries', 'ডেলিভারি'), ('products', 'পণ্য'), ('reviews', 'রিভিউ')], max_length=20, verbose_name='মেট্রিক ধরন')),
                ('date', models.DateField(verbose_name='তারিখ')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='মান')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='মেটাডেটা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
            ],
            options={
                'verbose_name': 'এনালিটিক্স ডেটা',
                'verbose_name_plural': 'এনালিটিক্স ডেটা',
                'ordering': ['-date', 'metric_type'],
                'unique_together': {('metric_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('notification_type', models.CharField(choices=[('order', 'অর্ডার'), ('delivery', 'ডেলিভারি'), ('payment', 'পেমেন্ট'), ('review', 'রিভিউ'), ('system', 'সিস্টেম'), ('promotion', 'প্রমোশন')], max_length=20, verbose_name='নোটিফিকেশন ধরন')),
                ('priority', models.CharField(choices=[('low', 'নিম্ন'), ('medium', 'মধ্যম'), ('high', 'উচ্চ'), ('urgent', 'জরুরি')], default='medium', max_length=10, verbose_name='অগ্রাধিকার')),
                ('is_read', models.BooleanField(default=False, verbose_name='পড়া হয়েছে')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='পড়া হয়েছে')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='অ্যাকশন URL')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='মেটাডেটা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='প্রাপক')),
            ],
            options={
                'verbose_name': 'নোটিফিকেশন',
                'verbose_name_plural': 'নোটিফিকেশন',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'তৈরি'), ('read', 'পড়া'), ('update', 'আপডেট'), ('delete', 'মুছে ফেলা'), ('login', 'লগইন'), ('logout', 'লগআউট'), ('error', 'ত্রুটি')], max_length=20, verbose_name='কর্ম')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='মডেল নাম')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='অবজেক্ট ID')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('level', models.CharField(choices=[('debug', 'ডিবাগ'), ('info', 'তথ্য'), ('warning', 'সতর্কতা'), ('error', 'ত্রুটি'), ('critical', 'ক্রিটিক্যাল')], default='info', max_length=10, verbose_name='লেভেল')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP ঠিকানা')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='ইউজার এজেন্ট')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='মেটাডেটা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'সিস্টেম লগ',
                'verbose_name_plural': 'সিস্টেম লগ',
                'ordering': ['-created_at'],
            },
        ),
    ]
