# Generated by Django 5.2.6 on 2025-09-06 06:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '১ ⭐'), (2, '২ ⭐⭐'), (3, '৩ ⭐⭐⭐'), (4, '৪ ⭐⭐⭐⭐'), (5, '৫ ⭐⭐⭐⭐⭐')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='রেটিং')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='শিরোনাম')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='মন্তব্য')),
                ('is_verified', models.BooleanField(default=False, verbose_name='যাচাইকৃত')),
                ('is_public', models.BooleanField(default=True, verbose_name='পাবলিক')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='সহায়ক ভোট')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেট হয়েছে')),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='গ্রাহক')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order', verbose_name='অর্ডার')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.productservice', verbose_name='পণ্য/সেবা')),
            ],
            options={
                'verbose_name': 'রিভিউ',
                'verbose_name_plural': 'রিভিউ',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_images/', verbose_name='ছবি')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='ক্যাপশন')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='রিভিউ')),
            ],
            options={
                'verbose_name': 'রিভিউ ছবি',
                'verbose_name_plural': 'রিভিউ ছবি',
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'স্প্যাম'), ('inappropriate', 'অনুপযুক্ত'), ('fake', 'জাল'), ('offensive', 'আপত্তিকর'), ('other', 'অন্যান্য')], max_length=20, verbose_name='কারণ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='বিবরণ')),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমান'), ('reviewed', 'পর্যালোচিত'), ('resolved', 'সমাধান'), ('dismissed', 'খারিজ')], default='pending', max_length=20, verbose_name='অবস্থা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='পর্যালোচনা হয়েছে')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL, verbose_name='রিপোর্টার')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review', verbose_name='রিভিউ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='পর্যালোচনা করেছেন')),
            ],
            options={
                'verbose_name': 'রিভিউ রিপোর্ট',
                'verbose_name_plural': 'রিভিউ রিপোর্ট',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='উত্তর')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেট হয়েছে')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_responses', to=settings.AUTH_USER_MODEL, verbose_name='উত্তরদাতা')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reviews.review', verbose_name='রিভিউ')),
            ],
            options={
                'verbose_name': 'রিভিউ উত্তর',
                'verbose_name_plural': 'রিভিউ উত্তর',
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(verbose_name='সহায়ক')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review', verbose_name='রিভিউ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'রিভিউ সহায়ক ভোট',
                'verbose_name_plural': 'রিভিউ সহায়ক ভোট',
                'unique_together': {('review', 'user')},
            },
        ),
    ]
