# Generated by Django 5.2.6 on 2025-09-06 06:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='নাম')),
                ('description', models.TextField(verbose_name='বিবরণ')),
                ('category', models.CharField(choices=[('food', 'খাবার'), ('medicine', 'ঔষধ'), ('gas', 'গ্যাস'), ('groceries', 'মুদি সামগ্রী'), ('electronics', 'ইলেকট্রনিক্স'), ('clothing', 'পোশাক'), ('books', 'বই'), ('other', 'অন্যান্য')], max_length=20, verbose_name='বিভাগ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='দাম (৳)')),
                ('is_available', models.BooleanField(default=True, verbose_name='উপলব্ধ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='ছবি')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেট হয়েছে')),
            ],
            options={
                'verbose_name': 'পণ্য/সেবা',
                'verbose_name_plural': 'পণ্য/সেবা',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='অর্ডার নম্বর')),
                ('delivery_type', models.CharField(choices=[('instant', 'তাত্ক্ষণিক'), ('scheduled', 'নির্ধারিত সময়')], default='instant', max_length=20, verbose_name='ডেলিভারি ধরন')),
                ('scheduled_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='নির্ধারিত ডেলিভারি সময়')),
                ('delivery_address', models.TextField(verbose_name='ডেলিভারি ঠিকানা')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='ডেলিভারি শহর')),
                ('delivery_instructions', models.TextField(blank=True, null=True, verbose_name='ডেলিভারি নির্দেশনা')),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমান'), ('confirmed', 'নিশ্চিত'), ('processing', 'প্রক্রিয়াধীন'), ('dispatched', 'প্রেরিত'), ('delivered', 'ডেলিভারি সম্পন্ন'), ('cancelled', 'বাতিল'), ('returned', 'ফেরত')], default='pending', max_length=20, verbose_name='অবস্থা')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='মোট পরিমাণ (৳)')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ডেলিভারি ফি (৳)')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='বিশেষ নির্দেশনা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেট হয়েছে')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='গ্রাহক')),
            ],
            options={
                'verbose_name': 'অর্ডার',
                'verbose_name_plural': 'অর্ডার',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমান'), ('confirmed', 'নিশ্চিত'), ('processing', 'প্রক্রিয়াধীন'), ('dispatched', 'প্রেরিত'), ('delivered', 'ডেলিভারি সম্পন্ন'), ('cancelled', 'বাতিল'), ('returned', 'ফেরত')], max_length=20, verbose_name='অবস্থা')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি হয়েছে')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='তৈরি করেছেন')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='অর্ডার')),
            ],
            options={
                'verbose_name': 'অর্ডার অবস্থা ইতিহাস',
                'verbose_name_plural': 'অর্ডার অবস্থা ইতিহাস',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='পরিমাণ')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='একক দাম (৳)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='মোট দাম (৳)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='অর্ডার')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.productservice', verbose_name='পণ্য/সেবা')),
            ],
            options={
                'verbose_name': 'অর্ডার আইটেম',
                'verbose_name_plural': 'অর্ডার আইটেম',
            },
        ),
    ]
