# Generated by Django 5.2.6 on 2025-09-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservice',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='স্টক পরিমাণ'),
        ),
    ]
