# Generated by Django 5.2.6 on 2025-09-13 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productservice_stock_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_notes',
            field=models.TextField(blank=True, null=True, verbose_name='বাতিলের নোট'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='বাতিলের কারণ'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='বাতিল হয়েছে'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL, verbose_name='বাতিল করেছেন'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_preference',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='রিফান্ড পছন্দ'),
        ),
    ]
